#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
    name: #@ data.values.appName
spec:
    replicas: 2
    selector:
        matchLabels:
            app: swaps-prices
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
    minReadySeconds: 5
    template:
        metadata:
            labels:
                app: #@ data.values.appName
        spec:
            containers:
                - name: #@ data.values.appName
                  image: IMAGE_NAME
                  ports:
                      - containerPort: 3030
                  resources:
                      requests:
                          cpu: 100m
                      limits:
                          cpu: 100m
